image:
  file: .gitpod.Dockerfile
# ports:
#   - port: 3000  
#     onOpen: open-preview
tasks:
  - name: Install Python Package
    init: pip install -e .

vscode:
  extensions:
    - ms-python.python