image:
  file: .gitpod.Dockerfile
tasks:
  - name: Install Python Package
    init: pip install --upgrade pip && pip install -e ./bnet_package && pip install -r ./requirements.txt && pip install pylint
vscode:
  extensions:
    - ms-python.python
