image:
  file: .gitpod.Dockerfile
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
tasks:
  - name: Install Python Package
    init: pip install -e . && pip install pylint

vscode:
  extensions:
    - ms-python.python